FROM node:lts-alpine3.20

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

WORKDIR /user-app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN pnpm install
RUN pnpm run prisma:generate

RUN pnpm build

CMD ["pnpm", "run", "start-user-app"]
