name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Deploy the project
    environment: venmo-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: hussaintahir/paytm-monorepo:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull hussaintahir/paytm-monorepo:${{ github.sha }}
            sudo docker stop paytm-monorepo || true
            sudo docker rm paytm-monorepo || true
            sudo docker run -d -p 3000:3000 \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              --name paytm-monorepo hussaintahir/paytm-monorepo:${{ github.sha }}
