name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Deploy the project
    environment: venmo-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: hussaintahir/paytm-monorepo:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            #!/bin/bash
            set -e

            echo "Starting deployment process..."

            echo "Stopping and removing existing containers..."
            sudo docker stop $(sudo docker ps -aq) || echo "No containers to stop"
            sudo docker rm $(sudo docker ps -aq) || echo "No containers to remove"

            echo "Removing existing images..."
            sudo docker rmi $(sudo docker images -q) || echo "No images to remove"

            echo "Removing volumes..."
            volumes=$(sudo docker volume ls -q)
            if [ -n "$volumes" ]; then
                sudo docker volume rm $volumes || echo "No volumes to remove"
            else
                echo "No volumes to remove"
            fi

            echo "Cleaning up any leftover data..."
            sudo docker system prune -af --volumes

            echo "Pulling new image..."
            sudo docker pull hussaintahir/paytm-monorepo:${{ github.sha }}

            echo "Starting new container..."
            container_id=$(sudo docker run -d -p 3000:3000 \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              --name paytm-monorepo hussaintahir/paytm-monorepo:${{ github.sha }})

            echo "Verifying deployment..."
            if [ $(sudo docker ps -q -f name=paytm-monorepo) ]; then
                echo "Deployment successful. Container ID: $container_id"
            else
                echo "Deployment failed. Container did not start properly."
                exit 1
            fi

            echo "Deployment process completed."
